### ISSUE TITLE
协议被硬编码以及端口号问题

### ISSUE THREAD

**Issue by wwek** [XdpCs/ComfyUIClient#19]
问题1:
rt
httpURL:    "https://" + serverAddress + ":" + port,

通常情况 ComfyUI 是 http协议，这里不能写死协议

问题2：
端口号是否需要单独分离为一个参数， 有我不知道的使用场景么

建议：
直接采用endpoint / baseurl这种概念。  直接一个参数即可
ps： ws的问题，直接抽取 endpoint的host即可

**Comment by XdpCs** [comment]
I will check it. I am on vacation.
